### ISSUE TITLE
Avoid warning in certain functions/JSX attributes

### ISSUE THREAD

**Issue by bnjmnt4n** [younesaassila/eslint-plugin-curly-quotes#15]
Thanks for creating this plugin!

I have a suggestion for avoiding warnings: typically we might use straight quotes in strings which are used as JSX properties (eg. `className`) or as arguments to certain functions (eg. `Error`), which we don't expect to be converted to curly quotes. I know we can use just disable the rule individually, but I believe making this configurable would be much more developer friendly.

Would you accept a PR to allow configuring JSX attributes/function names to avoid traversing?

**Comment by younesaassila** [comment]
Of course! Feel free to open a PR
